name: SpamShield
version: 1.1
main: me.tiger.spamshield.SpamShield
api-version: 1.21
author: 2b2t_names
description: Prevents repeated spam messages in chat
commands:
  spamshield:
    description: Enable or disable the spam filter
    usage: /spamshield <enable|disable>
